services:
  redis:
    container_name: "redis"
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - sisteminformasi_default

  web:
    container_name: "redisapi"
    build:
      context: .
    ports:
      - "3000:3000"
    networks:
      - sisteminformasi_default

networks:
  sisteminformasi_default:
    external: true
